### ISSUE TITLE
argo rollouts create analysisrun -> panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chengchengmu** [argoproj/argo-rollouts#1127]
## Summary 

What happened/what you expected to happen?

This command ` kubectl argo rollouts create analysisrun --from post-promotion -n ping-ccdev` fails with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x208842d]

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create.(*CreateAnalysisRunOptions).getAnalysisTemplate(0xc0005c5d40, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create/create.go:313 +0x19d
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create.NewCmdCreateAnalysisRun.func1(0xc000301b80, 0xc0000a2740, 0x0, 0x4, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create/create.go:255 +0x729
github.com/spf13/cobra.(*Command).execute(0xc000301b80, 0xc0000a26c0, 0x4, 0x4, 0xc000301b80, 0xc0000a26c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000301080, 0xc000301080, 0x264f2a0, 0xc00000e010)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0xbf
```

## Diagnostics

What version of Argo Rollouts are you running?
```
kubectl-argo-rollouts: v0.10.2+54343d8
  BuildDate: 2020-12-17T20:46:22Z
  GitCommit: 54343d8c9eb1e4b9f7e87b3da533530199916733
  GitTreeState: clean
  GoVersion: go1.13.1
  Compiler: gc
  Platform: darwin/amd64
```

```
# There is no log associated to this command
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by chengchengmu** [comment]
Found that the issue is caused by a difference of version between kubectl-argo-rollouts and the argo-rollouts deployment.
I am closing this bug ticket.

Would it be possible to display an error message showing an incomptibility between cli and deployment rather than a segfault ?
