### ISSUE TITLE
DataDog nil pointer dereference

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1444]
## Summary 

User reported the following panic in logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5a9ee2]

goroutine 227 [running]:
net/url.(*URL).Query(0x0, 0x2)
	/usr/local/go/src/net/url/url.go:1110 +0x22
github.com/argoproj/argo-rollouts/metricproviders/datadog.(*Provider).Run(0xc0006fc1e0, 0xc000da64e0, 0xc0008e4600, 0x1b, 0xc000cbad00, 0x2, 0x0, 0x0, 0x0, 0xc000cbad02, ...)
	/go/src/github.com/argoproj/argo-rollouts/metricproviders/datadog/datadog.go:86 +0x169
github.com/argoproj/argo-rollouts/analysis.(*Controller).runMeasurements.func1(0xc000e9e4a4, 0xc000da64e0, 0x2e07888, 0x0, 0x0, 0xc000e9e4b0, 0xc00044cf30, 0xc000ea6700, 0xc0008e4600, 0x1b, ...)
	/go/src/github.com/argoproj/argo-rollouts/analysis/analysis.go:280 +0xe35
created by github.com/argoproj/argo-rollouts/analysis.(*Controller).runMeasurements
	/go/src/github.com/argoproj/argo-rollouts/analysis/analysis.go:251 +0x278
```

## Diagnostics

What version of Argo Rollouts are you running? unsure

Here was affected code. It is likely caused by misconfiguration, but we should handle it.

```golang
func (p *Provider) Run(run *v1alpha1.AnalysisRun, metric v1alpha1.Metric) v1alpha1.Measurement {
	startTime := metav1.Now()

	// Measurement to pass back
	measurement := v1alpha1.Measurement{
		StartedAt: &startTime,
	}

	endpoint := "https://api.datadoghq.com/api/v1/query"
	if p.config.Address != "" {
		endpoint = p.config.Address + "/api/v1/query"
	}

	url, _ := url.Parse(endpoint)

	now := unixNow()
	var interval int64 = 300
	if metric.Provider.Datadog.Interval != "" {
		expDuration, err := metric.Provider.Datadog.Interval.Duration()
		if err != nil {
			return metricutil.MarkMeasurementError(measurement, err)
		}
		// Convert to seconds as DataDog expects unix timestamp
		interval = int64(expDuration.Seconds())
	}

	q := url.Query() // panic
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
We should not be ignoring this error to URL parse:

```
	endpoint := "https://api.datadoghq.com/api/v1/query"
	if p.config.Address != "" {
		endpoint = p.config.Address + "/api/v1/query"
	}

	url, _ := url.Parse(endpoint)
```
