### ISSUE TITLE
Panic Loop in Controller Rollout syncHandler

### ISSUE THREAD

**Issue by gavin-db** [argoproj/argo-rollouts#1630]
## Summary 

We encountered a syncHandler panic loop in the Argo Rollouts controller when updating a Rollout under the following conditions:

1. A new version of a Rollout (named apiProxy) was released with its replica count increased from 8 to 10. 
2. Argo attempted to scale the base replicaset from 8 -> 10 before scaling the canary replicaset (which was left at 0). 
3. The base replicaset failed to scale, because stable pods were incompatible with a ConfigMap that was deployed alongside the new service version.
4. The controller encountered an invalid memory address error and repeatedly failed to sync the Rollout with the following repeated runtime error:

> time="2021-10-20T03:19:53Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 307 [running]:\nruntime/debug.Stack(0xc002ff7118, 0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1.1(0xc003829b90, 0xc002ff7af0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:149 +0x5b\npanic(0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/argoproj/argo-rollouts/utils/replicaset.GetPodTemplateHash(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/replicaset/replicaset.go:521\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileBackgroundAnalysisRun(0xc0038b7400, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:331 +0x15f\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileAnalysisRuns(0xc0038b7400, 0xc0038b7400, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:92 +0xd77\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).syncReplicasOnly(0xc0038b7400, 0x2157a01, 0x17, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/sync.go:311 +0x167\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcile(0xc0038b7400, 0xc00383c600, 0xc0038b7400)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/context.go:78 +0x193\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).syncHandler(0xc00015e380, 0xc0073d4210, 0x13, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:391 +0x630\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1(0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:153 +0x7c\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc002ff7e60, 0xc000506cc0, 0x1dabbc0, 0xc002acb800, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:157 +0x326\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc002ff7e60, 0xc000506cc0, 0x100000000406f01)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:171 +0x9a\ngithub.com/argoproj/argo-rollouts/utils/controller.RunWorker(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:104\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).Run.func1()\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:321 +0xa5\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0077929b0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0077929b0, 0x245e6e0, 0xc000dee0c0, 0xc00089e001, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:156 +0x9b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0077929b0, 0x3b9aca00, 0x0, 0x1326d316e745301, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0077929b0, 0x3b9aca00, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-rollouts/rollout.(*Controller).Run\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:320 +0xac\n" namespace=production rollout=apiproxy

As a result of this , apiProxy failed to progress (although its status remained "progressing"), and the Rollout had to be manually redeployed to resolve the issue.

The primary issue here is the invalid memory exception that was encountered in the Argo Rollouts controller. Argo is trying to create a new Analysis Run for the canary ReplicaSet. While creating the new analysis run Argo is trying to read the template hash from the canary ReplicaSet, which does not exist because the canary ReplicaSet is waiting for the base ReplicaSet to scale.
```
podHash := replicasetutil.GetPodTemplateHash(c.newRS)
GetPodTemplateHash function is throwing a NPE as the RS is null
func GetPodTemplateHash(rs *appsv1.ReplicaSet) string {
	if rs.Labels == nil { <----- HERE
		return ""
	}
	return rs.Labels[v1alpha1.DefaultRolloutUniqueLabelKey]
} 
```

The specification does say that the ReplicaSet can be null:
```
// newRS is the "new" ReplicaSet. Also referred to as current, or desired.
// newRS will be nil when the pod template spec changes.
newRS *appsv1.ReplicaSet
```
So the fix is to handle that condition in `GetPodTemplateHash`, which should be:
```
if rs == nil || rs.Labels == nil {
  ...
}
```

**Note:** This issue highlights a difference between Rollouts and Deployments when increasing a replica count.  A Deployment will scale the canary ReplicaSet. Rollouts will instead attempt to scale the stable ReplicaSet before scaling the canary ReplicaSet. Because of this behavior, Rollouts cannot be deployed with non-backwards compatible ConfigMaps when changing replica counts, but Deployments can. Per discussions with maintainers, "Unlike deployments. Rollout is always constantly balancing between what it considers “stable” and the desired. Interrupted updates will cause you to start over from the first canary step." This means that whenever a release begins, Argo will always ensure that Stable is at 100% before proceeding, so that it can manage things like progressive traffic shifting correctly.

## Diagnostics

What version of Argo Rollouts are you running?
`version=vdb_unofficial_v1.1+46a2d53`

```
# Controller Logs (after restart) - full controller logs available upon request
time="2021-10-20T01:09:21Z" level=info msg="Syncing replicas only (userPaused false, isScaling: true)" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Start processing" resource=production/apiproxy
time="2021-10-20T01:09:21Z" level=error msg="Failed to process: secret \"argo-rollouts-notification-secret\" not found" resource=production/apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Enqueueing parent of production/apiproxy-56664b8464: Rollout production/apiproxy"
time="2021-10-20T01:09:21Z" level=info msg="Scaled up ReplicaSet apiproxy-56664b8464 (revision 4) from 5 to 8" event_reason=ScalingReplicaSet namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Not finished reconciling stableRS" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Reconciliation completed" generation=10 namespace=production resourceVersion=910729589 rollout=apiproxy time_ms=46.340999000000004
time="2021-10-20T01:09:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"production\", Name:\"apiproxy\", UID:\"d9dda8e1-42e8-4e4b-a7a6-7b857461575a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"910729589\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up ReplicaSet apiproxy-56664b8464 (revision 4) from 5 to 8"
time="2021-10-20T01:09:21Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 311 [running]:\nruntime/debug.Stack(0xc0050bd118, 0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1.1(0xc005225880, 0xc0050bdaf0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:149 +0x5b\npanic(0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/argoproj/argo-rollouts/utils/replicaset.GetPodTemplateHash(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/replicaset/replicaset.go:521\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileBackgroundAnalysisRun(0xc0064fd800, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:331 +0x15f\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileAnalysisRuns(0xc0064fd800, 0xc0064fd801, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:92 +0xd77\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).syncReplicasOnly(0xc0064fd800, 0x2157a01, 0x17, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/sync.go:311 +0x167\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcile(0xc0064fd800, 0xc005380600, 0xc0064fd800)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/context.go:78 +0x193\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).syncHandler(0xc00015e380, 0xc0073d4210, 0x13, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:391 +0x630\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1(0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:153 +0x7c\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc0050bde60, 0xc000506cc0, 0x1dabbc0, 0xc0073a8ea0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:157 +0x326\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc0050bde60, 0xc000506cc0, 0x1)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:171 +0x9a\ngithub.com/argoproj/argo-rollouts/utils/controller.RunWorker(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:104\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).Run.func1()\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:321 +0xa5\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0077929f0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0077929f0, 0x245e6e0, 0xc0010c0660, 0x1, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:156 +0x9b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0077929f0, 0x3b9aca00, 0x0, 0x1, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0077929f0, 0x3b9aca00, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-rollouts/rollout.(*Controller).Run\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:320 +0xac\n" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=error msg="rollout syncHandler error: Recovered from Panic" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="rollout syncHandler queue retries: 3 : key \"production/apiproxy\"" namespace=production rollout=apiproxy
E1020 01:09:21.457861       1 controller.go:174] Recovered from Panic
time="2021-10-20T01:09:21Z" level=info msg="Started syncing rollout" generation=10 namespace=production resourceVersion=910729594 rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Syncing replicas only (userPaused false, isScaling: true)" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Reconciling 1 old ReplicaSets (total pods: 4)" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Found 4 available pods in old RS production/apiproxy-7c8b7bffb" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Reconciliation completed" generation=10 namespace=production resourceVersion=910729594 rollout=apiproxy time_ms=5.9621379999999995
time="2021-10-20T01:09:21Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 311 [running]:\nruntime/debug.Stack(0xc0050bd118, 0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1.1(0xc005622540, 0xc0050bdaf0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:149 +0x5b\npanic(0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/argoproj/argo-rollouts/utils/replicaset.GetPodTemplateHash(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/replicaset/replicaset.go:521\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileBackgroundAnalysisRun(0xc003ec1c00, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:331 +0x15f\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcileAnalysisRuns(0xc003ec1c00, 0xc003ec1c00, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/analysis.go:92 +0xd77\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).syncReplicasOnly(0xc003ec1c00, 0x2157a01, 0x17, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/sync.go:311 +0x167\ngithub.com/argoproj/argo-rollouts/rollout.(*rolloutContext).reconcile(0xc003ec1c00, 0xc00562a600, 0xc003ec1c00)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/context.go:78 +0x193\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).syncHandler(0xc00015e380, 0xc0073d4210, 0x13, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:391 +0x630\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1(0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:153 +0x7c\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc0050bde60, 0xc000506cc0, 0x1dabbc0, 0xc0073a8ea0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:157 +0x326\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem(0x24bf630, 0xc0001c4f00, 0x213f955, 0x7, 0xc0050bde60, 0xc000506cc0, 0x1)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:171 +0x9a\ngithub.com/argoproj/argo-rollouts/utils/controller.RunWorker(...)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:104\ngithub.com/argoproj/argo-rollouts/rollout.(*Controller).Run.func1()\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:321 +0xa5\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0077929f0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0077929f0, 0x245e6e0, 0xc0010c0660, 0x1, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:156 +0x9b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0077929f0, 0x3b9aca00, 0x0, 0x1, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0077929f0, 0x3b9aca00, 0xc0000def60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-rollouts/rollout.(*Controller).Run\n\t/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:320 +0xac\n" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=error msg="rollout syncHandler error: Recovered from Panic" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="rollout syncHandler queue retries: 4 : key \"production/apiproxy\"" namespace=production rollout=apiproxy
E1020 01:09:21.464138       1 controller.go:174] Recovered from Panic
time="2021-10-20T01:09:21Z" level=info msg="Started syncing rollout" generation=10 namespace=production resourceVersion=910729594 rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Syncing replicas only (userPaused false, isScaling: true)" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Reconciling 1 old ReplicaSets (total pods: 4)" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Found 4 available pods in old RS production/apiproxy-7c8b7bffb" namespace=production rollout=apiproxy
time="2021-10-20T01:09:21Z" level=info msg="Reconciliation completed" generation=10 namespace=production resourceVersion=910729594 rollout=apiproxy time_ms=4.886332
time="2021-10-20T01:09:21Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 311 [running]:\nruntime/debug.Stack(0xc0050bd118, 0x1e557e0, 0x322ca40)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-rollouts/utils/controller.processNextWorkItem.func1.1.1(0xc005698e70, 0xc0050bdaf0)\n\t/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:149 +0x5b\npanic(


# Rollout Status
Status:
  HPA Replicas:        8
  Available Replicas:  8
  Blue Green:
  Canary:
  Conditions:
    Last Transition Time:  2021-10-20T00:57:28Z
    Last Update Time:      2021-10-20T00:57:28Z
    Message:               RolloutCompleted
    Reason:                RolloutCompleted
    Status:                False
    Type:                  Completed
    Last Transition Time:  2021-10-20T01:09:21Z
    Last Update Time:      2021-10-20T01:09:21Z
    Message:               Rollout "apiproxy" is progressing.
    Reason:                ReplicaSetUpdated
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2021-10-20T01:09:21Z
    Last Update Time:      2021-10-20T01:09:21Z
    Message:               Rollout does not have minimum availability
    Reason:                AvailableReason
    Status:                False
    Type:                  Available
    Last Transition Time:  2021-10-20T01:09:21Z
    Last Update Time:      2021-10-20T01:09:21Z
    Message:               Rollout is paused
    Reason:                RolloutPaused
    Status:                False
    Type:                  Paused
  Current Pod Hash:        5c4957bf95
  Current Step Hash:       56fddb67f8
  Current Step Index:      0
  Message:                 more replicas need to be updated
  Observed Generation:     10
  Phase:                   Progressing
  Ready Replicas:          8
  Replicas:                8
  Selector:                app=apiproxy
  Stable RS:               56664b8464
Events:                    <none>
gavin.kliger@C02CD0T0MD6R:~/universe$ kubectl get rollout apiproxy -n production 
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE
apiproxy   10              8                                           8
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by agrawroh** [comment]
@jessesuen Could you please assign this to me?
