### ISSUE TITLE
kubectl-argo-rollouts panic while watching progress

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1747]
## Summary 

We were running the kubectl-argo-rollouts plugin to wait for a rollout to complete.  Right near the end of the rollout, it paniced even though the rollout had completed successfully.

The script waits for two rollouts to complete, e.g.
```
kubectl argo rollouts status rollout1
kubectl argo rollouts status rollout2
```

So I'm not 100% sure if it was at the end of watching rollout1 that it happened, or when it tried to watch rollout2.

This has only happened once and isn't a huge issue, but I just thought I'd share in case something jumps out at you.  Let me know if I can provide any other information

## Diagnostics

What version of Argo Rollouts are you running?

Rollout controller 1.1.1

Plugin was just the latest from a few months ago:
```
 BuildDate: 2021-10-11T20:19:55Z
  GitCommit: ff3471a2fc3ccb90dbb1f370d7e399ff3064043a
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: linux/amd64
```

Plugin output: https://gist.github.com/bpoland/020e37d181115abd43d4c2c42bd61767

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by Temikus** [comment]
Can confirm this started happening only after upgrading from `1.1.0` to `1.1.1`

**Comment by Temikus** [comment]
One more addition here - something is wrong with the controller as well. It looks like to be a combination of things. 1.1.0 Kubectl + 1.1.1 controller seem to have the same issue.

```
Paused - CanaryPauseStep
--
  | Paused - CanaryPauseStep
  | Paused - CanaryPauseStep
  | Progressing - waiting for all steps to complete
  | Healthy
  | E0118 17:58:27.419321     245 runtime.go:78] Observed a panic: "send on closed channel" (send on closed channel)
  | goroutine 42 [running]:
  | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c95ea0, 0x2897310)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/runtime/runtime.go:74 +0x95
  | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/runtime/runtime.go:48 +0x86
  | panic(0x1c95ea0, 0x2897310)
  | /usr/local/go/src/runtime/panic.go:965 +0x1b9
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/status.NewCmdStatus.func1.1(0xc0011e5080)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/status/status.go:66 +0x3e
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*RolloutViewController).RegisterCallback.func1(0x1ef4180, 0xc0011e5080)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:203 +0x42
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).processNextWorkItem(0xc00089ac30, 0x203000)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:164 +0x16e
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).Run.func1()
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:143 +0x36
  | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c05250)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:155 +0x5f
  | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c05250, 0x28ba4e0, 0xc00079a060, 0x1, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:156 +0x9b
  | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c05250, 0x3b9aca00, 0x0, 0x1, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:133 +0x98
  | k8s.io/apimachinery/pkg/util/wait.Until(0xc000c05250, 0x3b9aca00, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:90 +0x4d
  | created by github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).Run
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:142 +0xa5
  | panic: send on closed channel [recovered]
  | panic: send on closed channel
  |  
  | goroutine 42 [running]:
  | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/runtime/runtime.go:55 +0x109
  | panic(0x1c95ea0, 0x2897310)
  | /usr/local/go/src/runtime/panic.go:965 +0x1b9
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/status.NewCmdStatus.func1.1(0xc0011e5080)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/status/status.go:66 +0x3e
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*RolloutViewController).RegisterCallback.func1(0x1ef4180, 0xc0011e5080)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:203 +0x42
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).processNextWorkItem(0xc00089ac30, 0x203000)
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:164 +0x16e
  | github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).Run.func1()
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:143 +0x36
  | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c05250)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:155 +0x5f
  | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c05250, 0x28ba4e0, 0xc00079a060, 0x1, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:156 +0x9b
  | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c05250, 0x3b9aca00, 0x0, 0x1, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:133 +0x98
  | k8s.io/apimachinery/pkg/util/wait.Until(0xc000c05250, 0x3b9aca00, 0xc000114f60)
  | /go/pkg/mod/k8s.io/apimachinery@v0.21.0-alpha.0/pkg/util/wait/wait.go:90 +0x4d
  | created by github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller.(*viewController).Run
  | /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/viewcontroller/viewcontroller.go:142 +0xa5


```

**Comment by Temikus** [comment]
@jessesuen Thank you so much for fixing this! Can we please ask for a release with a fix? 🙏 This is affecting us pretty severely.
