### ISSUE TITLE
./server/static/index.html missing on 1.3.0-rc1

### ISSUE THREAD

**Issue by jSherz** [argoproj/argo-rollouts#2191]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've inclued the version of argo rollouts.

**Describe the bug**

When trying to view the dashboards as part of kubectl plugin or service as part of 1.3.0-rc1, the following error is seen:

```
kubectl argo rollouts version
```

```
kubectl-argo-rollouts: v1.3.0-rc1+0ec5ac1
  BuildDate: 2022-07-29T18:58:16Z
  GitCommit: 0ec5ac18a307ae579787b974e17f3e4c0bf41cff
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
```

Trying via CLI:

```
kubectl argo rollouts dashboard -n argocd
```

```

ERRO[0000] An error occurred on opening the inputfile
Does the file exist?
Have you got access to it? 
panic: open ./server/static/index.html: no such file or directory

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/server.withRootPath({0x205b582, 0x8})
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:103 +0x4e5
github.com/argoproj/argo-rollouts/server.(*ArgoRolloutsServer).newHTTPServer(0xc0000c9800, {0x23eb210, 0xc000bd0780}, 0x0?)
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:156 +0x428
github.com/argoproj/argo-rollouts/server.(*ArgoRolloutsServer).Run(0xc0000c9800, {0x23eb210?, 0xc000bd0780?}, 0xc1c, 0x1)
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:186 +0x56
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/dashboard.NewCmdDashboard.func1(0xc00031ac80?, {0xc000bcb280?, 0x2?, 0x2?})
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go:33 +0x148
github.com/spf13/cobra.(*Command).execute(0xc00031ac80, {0xc000bcb260, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e8c80)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0x9a
```

Via the service/pod installation using the dashboard install YML file:

```
kubectl -n argo-rollouts logs argo-rollouts-dashboard-644df6d84f-sgcq9
```

```
panic: open ./server/static/index.html: no such file or directory

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/server.withRootPath({0x205b582, 0x8})
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:103 +0x4e5
github.com/argoproj/argo-rollouts/server.(*ArgoRolloutsServer).newHTTPServer(0xc000313bc0, {0x23eb210, 0xc0006a7200}, 0x0?)
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:156 +0x428
github.com/argoproj/argo-rollouts/server.(*ArgoRolloutsServer).Run(0xc000313bc0, {0x23eb210?, 0xc0006a7200?}, 0xc1c, 0x1)
	/go/src/github.com/argoproj/argo-rollouts/server/server.go:186 +0x56
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/dashboard.NewCmdDashboard.func1(0xc0004a2c80?, {0x34846e0?, 0x0?, 0x0?})
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go:33 +0x148
github.com/spf13/cobra.(*Command).execute(0xc0004a2c80, {0x34846e0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004b6280)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0x9a

```

**To Reproduce**

Install 1.3.0-rc1 as a kubectl plugin or via [dashboard-install.yaml](https://github.com/argoproj/argo-rollouts/releases/download/v1.3.0-rc1/dashboard-install.yaml).

**Expected behavior**

Dashboard is available and pod does not crash loop.

**Screenshots**

N/A

**Version**

As above:

```
kubectl-argo-rollouts: v1.3.0-rc1+0ec5ac1
```

**Logs**

As above.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by leoluz** [comment]
@jSherz Thanks for pointing this out. We fixed this issue in `master` and also cherry-picked in `release-1.3` branch. Are you able to give it a try with one of the two branches? We are waiting on another bug fix before releasing rc2.
