### ISSUE TITLE
Controller panics due to NPE in service.go

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#24]
Controller fails if encountered service which belogs to rollout with nil strategy

**Logs**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ce729b]

goroutine 68 [running]:
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1e2fca0, 0x2cf6010)
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
github.com/argoproj/argo-rollouts/controller.(*Controller).getRolloutsForService(0xc0003febe0, 0xc0003da1e0, 0xc0003b17a0, 0xc00071bd78, 0xc00071bcd0, 0x3, 0x0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/controller/service.go:132 +0x1ab
github.com/argoproj/argo-rollouts/controller.(*Controller).handleService(0xc0003febe0, 0x1f9a900, 0xc0003da1e0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/controller/service.go:148 +0x4a
github.com/argoproj/argo-rollouts/controller.(*Controller).handleService-fm(0x1f9a900, 0xc0003da1e0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/controller/controller.go:147 +0x3e
github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc0005eb260, 0xc0005eb270, 0xc0005eb280, 0x1f9a900, 0xc0003da1e0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x102b753, 0xc00006edc8, 0x0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554 +0x21d
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc00082fe18, 0x102b262, 0xc0004913e0)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x89
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00006ef68)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00082ff68, 0xdf8475800, 0x0, 0x1e0ee01, 0xc0000acd80)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00006ef68, 0xdf8475800, 0xc0000acd80)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005f2e80)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x8d
github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache.(*processorListener).run-fm()
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004160d0, 0xc0005eb300)
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/Users/amatyushentsev/root/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by alexmt** [comment]
I would suggest to add panic handlers in event handlers: 

https://github.com/argoproj/argo-rollouts/blob/f2e93bfe1dfbe3861a1a00e5185faae4e67d3f9a/controller/controller.go#L123

**Comment by alexmt** [comment]
Also instead of loading all rollouts on each service update we should use informer, same as for replicaset
This is not directly related to this issue but change is few lines away from NPE fix :)

change:
https://github.com/argoproj/argo-rollouts/blob/f2e93bfe1dfbe3861a1a00e5185faae4e67d3f9a/controller/service.go#L126-L127

to
```
c.rolloutsLister.Rollouts(service.Namespace).List(metav1.ListOptions{})
```
