### ISSUE TITLE
Crash: nil pointer dereference 

### ISSUE THREAD

**Issue by mclarke47** [argoproj/argo-rollouts#571]
Controller crashed with the following error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1419b3e]

goroutine 332 [running]:
github.com/argoproj/argo-rollouts/utils/kubeclientmetrics.(*metricsRoundTripper).RoundTrip(0xc0004eec80, 0xc000715900, 0x18fe761, 0xd, 0xc001caa0b8)
	/go/src/github.com/argoproj/argo-rollouts/utils/kubeclientmetrics/metric.go:190 +0x43e
k8s.io/client-go/transport.(*bearerAuthRoundTripper).RoundTrip(0xc00038ab10, 0xc000715800, 0x18fbd79, 0xa, 0xc001652e60)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/transport/round_trippers.go:297 +0x266
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0004eece0, 0xc000715700, 0xc0004eece0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/transport/round_trippers.go:159 +0x1c0
net/http.send(0xc000715700, 0x1b51e80, 0xc0004eece0, 0x0, 0x0, 0x0, 0xc000f32590, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x43a
net/http.(*Client).send(0xc00038ab40, 0xc000715700, 0x0, 0x0, 0x0, 0xc000f32590, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc00038ab40, 0xc000715700, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
k8s.io/client-go/rest.(*Request).Watch(0xc003610f00, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/rest/request.go:594 +0x1b7
k8s.io/client-go/dynamic.(*dynamicResourceClient).Watch(0xc003bcaf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/dynamic/simple.go:286 +0x2a7
github.com/argoproj/argo-rollouts/utils/controller.WatchResource(0x1b518c0, 0xc00037e278, 0x0, 0x0, 0x191ba75, 0x13, 0x18fa5ea, 0x8, 0x191ba65, 0xf, ...)
	/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:53 +0x151
github.com/argoproj/argo-rollouts/utils/controller.WatchResourceWithExponentialBackoff(0xc0000e2480, 0x1b518c0, 0xc00037e278, 0x0, 0x0, 0x191ba75, 0x13, 0x18fa5ea, 0x8, 0x191ba65, ...)
	/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:84 +0x15b
created by github.com/argoproj/argo-rollouts/rollout.(*RolloutController).Run
	/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:246 +0x313
```

**Comment by dthomson25** [comment]
Closed with https://github.com/argoproj/argo-rollouts/pull/603
