### ISSUE TITLE
The controller crashes when the resource unit is not set up correctly.

### ISSUE THREAD

**Issue by AnyISalIn** [argoproj/argo-rollouts#838]
## Summary 

What happened/what you expected to happen?

The controller crashes when the resource unit is not set up correctly.

```
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32i # <- incorrect unit
            cpu: 5m
```

## Diagnostics

What version of Argo Rollouts are you running?

v0.9.1

# Paste the logs from the rollout controller

# Logs for the entire controller:
```
kubectl logs -n argo-rollouts deployment/argo-rollouts

time="2020-11-11T10:37:46Z" level=info msg="Reconciliation completed" namespace=default rollout=default-argo-samples-bluegreen-helm-guestbook time_ms=1.31261
time="2020-11-11T10:37:46Z" level=warning msg="Error updating application: v1alpha1.Rollout.Status: v1alpha1.RolloutStatus.Spec: v1alpha1.RolloutSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|ory\":\"32i\"}}}]}}},\"s|..., bigger context ...|\"resources\":{\"requests\":{\"cpu\":\"5m\",\"memory\":\"32i\"}}}]}}},\"status\":{\"HPAReplicas\":6,\"availableReplic|..." namespace=default rollout=rollouts-demo
time="2020-11-11T10:37:46Z" level=info msg="Reconciliation completed" namespace=default rollout=rollouts-demo time_ms=16.288962
time="2020-11-11T10:37:46Z" level=error msg="rollout syncHandler error: v1alpha1.Rollout.Status: v1alpha1.RolloutStatus.Spec: v1alpha1.RolloutSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|ory\":\"32i\"}}}]}}},\"s|..., bigger context ...|\"resources\":{\"requests\":{\"cpu\":\"5m\",\"memory\":\"32i\"}}}]}}},\"status\":{\"HPAReplicas\":6,\"availableReplic|..." namespace=default rollout=rollouts-demo
E1111 10:37:46.339932       1 controller.go:170] v1alpha1.Rollout.Status: v1alpha1.RolloutStatus.Spec: v1alpha1.RolloutSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|ory":"32i"}}}]}}},"s|..., bigger context ...|"resources":{"requests":{"cpu":"5m","memory":"32i"}}}]}}},"status":{"HPAReplicas":6,"availableReplic|...
time="2020-11-11T10:37:46Z" level=info msg="Rollout has executed every step" namespace=sample rollout=helloworld-v0
time="2020-11-11T10:37:46Z" level=info msg="New RS has successfully progressed" namespace=sample rollout=helloworld-v0
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=info msg="No status changes. Skipping patch" namespace=sample rollout=helloworld-v0
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=info msg="Reconciliation completed" namespace=sample rollout=helloworld-v0 time_ms=2.1134090000000003
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
time="2020-11-11T10:37:46Z" level=warning msg="Failed to convert Rollout from Unstructured object: unable to parse quantity's suffix"
E1111 10:37:46.340675       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 166 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x176be20, 0x292cd40)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x176be20, 0x292cd40)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/argoproj/argo-rollouts/utils/service.GetRolloutServiceKeys(0x0, 0xc000670100, 0x0, 0xc000476f00)
        /go/src/github.com/argoproj/argo-rollouts/utils/service/service.go:25 +0x9f
github.com/argoproj/argo-rollouts/rollout.NewController.func4(0x19824e0, 0xc00033ac00, 0x19824e0, 0xc000670100)
        /go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:208 +0x98
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x10, 0x10, 0xc0002dac80)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:656 +0x188
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc001759dd8, 0x0, 0xc00062bdf8)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062bf40)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001759f40, 0xdf8475800, 0x0, 0x1, 0xc000548120)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0003a6400)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002e44c0, 0xc0007c0080)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x400 pc=0x158dbaf]

goroutine 166 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x176be20, 0x292cd40)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/argoproj/argo-rollouts/utils/service.GetRolloutServiceKeys(0x0, 0xc000670100, 0x0, 0xc000476f00)
        /go/src/github.com/argoproj/argo-rollouts/utils/service/service.go:25 +0x9f
github.com/argoproj/argo-rollouts/rollout.NewController.func4(0x19824e0, 0xc00033ac00, 0x19824e0, 0xc000670100)
        /go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:208 +0x98
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x10, 0x10, 0xc0002dac80)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:656 +0x188
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc001759dd8, 0x0, 0xc00062bdf8)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062bf40)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001759f40, 0xdf8475800, 0x0, 0x1, 0xc000548120)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0003a6400)
        /go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002e44c0, 0xc0007c0080)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
```
# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
This is fixed in v0.9.3
