### ISSUE TITLE
kubectl argo rollouts create segfaults

### ISSUE THREAD

**Issue by MarkSRobinson** [argoproj/argo-rollouts#944]
## Summary 

I ran  `kubectl argo rollouts create -f analysis-run.yaml -n msr-test` and I got

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2087259]

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create.(*CreateOptions).createResource(0xc0002aa540, 0x7ffeefbff8b7, 0x11, 0x15, 0xc0000fe420, 0xc0005f7d28, 0x1db66d4)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create/create.go:183 +0xba9
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create.NewCmdCreate.func1(0xc000307600, 0xc0002cff00, 0x0, 0x4, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/create/create.go:89 +0xda
github.com/spf13/cobra.(*Command).execute(0xc000307600, 0xc0002cfec0, 0x4, 0x4, 0xc000307600, 0xc0002cfec0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000306dc0, 0xc000306dc0, 0x264f220, 0xc0000a2000)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0xbf
```

analysis-run.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
    - name: success-rate
      interval: 15s
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] >= 1
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(alertmanager_alerts)
```

## Diagnostics

```
$> kubectl version
 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-15T00:59:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Rollouts are you running?

```
kubectl argo rollouts version

kubectl-argo-rollouts: v0.10.0+3837eab
  BuildDate: 2020-11-13T23:03:54Z
  GitCommit: 3837eab0eae57d28498c8d946325bb73090663a4
  GitTreeState: clean
  GoVersion: go1.13.1
  Compiler: gc
  Platform: darwin/amd64
```
# Paste the logs from the rollout controller

No logs emitted from controller.

```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/932
